# Settings for libraries used by specific LAMMPS packages
# this file is auto-edited when those packages are included/excluded

PKG_INC =   
PKG_PATH =  
PKG_LIB =   
PKG_CPP_DEPENDS = 
PKG_LINK_DEPENDS = 

PKG_SYSINC =  $(molfile_SYSINC) 
PKG_SYSLIB =  $(molfile_SYSLIB) 
PKG_SYSPATH = $(molfile_SYSPATH) 
